### ISSUE TITLE
Testing library decision

### ISSUE THREAD

**Issue by digiguru** [hogsmill/no-estimates#3]
Hi folks. Steve invited me to write some tests for this. I'm happy to open it up and do so. Would you like front-end tests or unit tests in the first instance.

Front end allows us to confirm the behaviour as it occurs to the users so it's more valuable - but it's slow to run and won't run on free CI servers reliably like CircleCI.

Unit is faster to run but arguably less useful.

I would also like to add CI so if you'd be happy I can set something up in CircleCI to confirm the project is ready on every commit.

Your views?

**Comment by jjleight** [comment]
I think unit first due to the points you made about speed of running, then front-end test can form a sub-set of the unit tests where possible.

**Comment by hogsmill** [comment]
I think any tests would be beneficial; we're not under any time/deadline pressures, so no worries if tests take a while to run. I'd be most interested in "regression" type tests rather than unit - the sort of stuff that can catch breaking stuff if we do a massive re-factor :-)

Shoud we all have a quick Zoom next week to discuss? When's a good time and I'll set up :-)

**Comment by jjleight** [comment]
Fair point! It's definitely worth discussing where tests should sit to get the most value, for me it's really important to put the tests at the right level and avoid duplication where possible to maximise the feedback loop.

**Comment by digiguru** [comment]
Well we have a regression test on #6 - have a look. I might add a more interactive example, but I want to focus on getting CI running them first.

**Comment by digiguru** [comment]
Okay so I've now got a simple Regression test running on a fork in CircleCI. I use Circle simply because it's what I've used historically.

It seems to work fine.

![image](https://user-images.githubusercontent.com/619436/92326182-2eb2c200-f048-11ea-9d59-125472d89039.png)

It even records a video of the test run to aid debugging.

I now have 2 options.

**Option 1 - Setup CircleCI on hogsmill**
@hogsmill needs to setup a circleCI account to get it running for his github area:
![image](https://user-images.githubusercontent.com/619436/92326211-66216e80-f048-11ea-9ec8-44d0309c14a6.png)

**Option 2 - Migrate to Github Actions**
I've never used github actions before but it's now publically available. I can research this as it might be cleaner.

**Comment by digiguru** [comment]
Cool - I got github actions. Now if you have a branch in Github and offer a pull request, it will run the tests on that PR and tell you if it's okay to merge within 3 mins.

Checkout [an example](https://github.com/hogsmill/no-estimates/pull/12/checks)

![image](https://user-images.githubusercontent.com/619436/92327398-6eca7280-f051-11ea-8621-8c65bd16f389.png)

Note the inclusion of a video file to aid debugging.

**Comment by digiguru** [comment]
Though't id give you insight into how the Github Actions work:

Firstly we name the github action
https://github.com/hogsmill/no-estimates/blob/c574837734647888459b01089a0e2f6426dc1ded/.github/workflows/blank.yml#L1
Then we trigger this on every push to the repository. You can trigger on other things like push to a specific branch (master) or when a PR is generated.
https://github.com/hogsmill/no-estimates/blob/c574837734647888459b01089a0e2f6426dc1ded/.github/workflows/blank.yml#L2
Now let's name a job and run it on a specific type of box - for us it's Ubuntu
https://github.com/hogsmill/no-estimates/blob/c574837734647888459b01089a0e2f6426dc1ded/.github/workflows/blank.yml#L3-L6
Step 1 - checkout the code
https://github.com/hogsmill/no-estimates/blob/c574837734647888459b01089a0e2f6426dc1ded/.github/workflows/blank.yml#L7
which is akin to the following lines in the `deploy.sh` script
https://github.com/hogsmill/no-estimates/blob/c574837734647888459b01089a0e2f6426dc1ded/deploy.sh#L7-L14
Now Step 2 - run e2e tests
https://github.com/hogsmill/no-estimates/blob/c574837734647888459b01089a0e2f6426dc1ded/.github/workflows/blank.yml#L8-L12
Step 3 - Always (even if it errors) upload anything in the /tests/e2e/videos folder of the project
https://github.com/hogsmill/no-estimates/blob/c574837734647888459b01089a0e2f6426dc1ded/.github/workflows/blank.yml#L13-L17

You can see the ease of Actions. You can make more complex scripts that actually run shell commands raw, but just like Node Modules abstract complex logic into simple packages, github actions abstract long shells scripts into simple references.

If you want to understand what one does - you go and have a look at the action logic:
https://github.com/cypress-io/github-action
