### ISSUE TITLE
Linting Decsion

### ISSUE THREAD

**Issue by digiguru** [hogsmill/no-estimates#4]
The code in this project has inconsistencies. Luckily ESLint can automatically fix to a preferred coding style. I like to know the preferred coding style, so please can we agree to some of the following styles....

*Semi-colons*
```
//Yes
this.socket.on('updateConnections', (data) => {
      this.$store.dispatch('updateConnections', data);
});

//vs
//No
this.socket.on('updateConnections', (data) => {
      this.$store.dispatch('updateConnections', data)
})
```

*Quotes*
```
//Single
this.socket.on('updateConnections', (data) => {
      this.$store.dispatch('updateConnections', data)
})
//vs
//Double
this.socket.on("updateConnections", (data) => {
      this.$store.dispatch("updateConnections", data)
})
```

*V-Bind Style*
```
Shorthand
  <div :foo="bar"/>
Longhand
  <div v-bind:foo="bar"/>
```

*Empty Components*
```
Short
<MyComponent/>

Long
<MyComponent></MyComponent>
```

**Comment by jjleight** [comment]
Sounds good to me!

**Comment by digiguru** [comment]
Cool, what's your preference....

- Semi-colons or no semi colons?
- Double or single quotes?
- Shorthand or longhand for v-bind style and for Empty Components?

**Comment by jjleight** [comment]
- no semi colons
- single quotes
- shorthand
😄

**Comment by digiguru** [comment]
Excellent. Do you have any uncommitted code? This is going to be a large-ish change so it's best to commit to a branch.

In fact I'll commit the new config settings first and put in guidance to run it on your code so that your code can be "fixed" using the same ruleset.

**Comment by jjleight** [comment]
I haven't got any uncommitted code for this project.

**Comment by digiguru** [comment]
If @hogsmill does please pull d50085358331d6e27290f4ccd60dd490fa83e6a3 from #5 into your code and follow the instructions on the pull request.

**Comment by digiguru** [comment]
Cool, #5 is ready for review

**Comment by digiguru** [comment]
Adding Cypress #6 triggered other linting issues that would be worth resolving, namely:

`no-unused-vars`
`no-undef`
`no-redeclare`

**Comment by digiguru** [comment]
I've applied these in #7
